name: routing_generator_builder
description: "Builder for routing_generator annotation"
version: 1.0.2

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.4.2
  source_gen: ^2.0.0
  dart_style: ^3.0.1
  code_builder: ^4.10.1
  path: ^1.9.1
  glob: ^2.1.3
  routing_generator:
    git: https://github.com/JonathanVegasP/routing_generator.git
  analyzer: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
